import Head from 'next/head'
import NavBar from '../NavBar';

const Header = () => {
  return (
    <>
      <Head>
        <title>Next.js Fundamentals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    </>
  )
}

export default Header;